name: Deploy TradeUp

on:
  push:
    branches: [ main ]

jobs:
  deploy-fontend:
    name: Deploy TradeUp Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Deploy to github pages website
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: AmazonPriime/amazonpriime.github.io
          branch: main
          folder: frontend
          target-folder: trade-up
          clean: true
          token: ${{ secrets.PAT }}
